config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # get 'home/index'

  root 'home#index'

  resources :posts
  resources :articles
  resources :home
  get "articles/crawling" => "articles#crawling", as: "crawling_articles"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates_uniqueness_of :url
  require 'selenium-webdriver'

  def self.snu
    Selenium::WebDriver::Chrome::Service.driver_path = "/usr/local/Caskroom/chromedriver/77.0.3865.40/chromedriver" # 설치한 크롬 드라이버 사용
    #Selenium::WebDriver::Chrome::Service.driver_path = '/Users/ju-young/.rbenv/shims/chromedriver-helper'
    #크롬 창 열지않고 크롤링 (헤드리스)
    options = Selenium::WebDriver::Chrome::Options.new # 크롬 헤드리스 모드 위해 옵션 설정
    options.add_argument('--disable-gApu') # 크롬 헤드리스 모드 사용 위해 disable-gpu setting
    options.add_argument('--headless') # 크롬 헤드리스 모드 사용 위해 headless setting

    # 실레니움 + 크롬 + 헤드리스 옵션으로 브라우저 실행
    @browser = Selenium::WebDriver.for :chrome, options: options

    #원하는 페이지로 이동
    @browser.navigate().to "https://gsis.snu.ac.kr/upcoming_events"

    #공지사항 제목 잡기
    sleep(1);
    @browser.find_element(css: "#snu_gsis > div.text-center > ul > li:nth-child(3) > a").click

    @content = @browser.find_elements(css: '#upcoming_events > div:nth-child(2) > div > table > tbody > tr')

    puts "#{@content.map{|x| x }}"


    @content.each do |t|
      # @date = t.find_element
      @title = t.find_element(tag_name: "a").text
      @url = t.find_element(tag_name: "a").attribute("href")
      # puts "#{@title} 이랑 #{@url}"
      Article.create(title: @title, url: @url, site: "서울대학교")
    end

    @browser.quit
  end
end

app/models/notice.rb
class Notice < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    # byebug
    @article = Article.all
    if params[:site] == "snu"
      @article = Article.snu
      # byebug
      @article = Article.all.order(created_at: :asc)
      respond_to do |format|
        format.js
      end
    end
    @article = @article.page(params[:page]).per(10)
  end

  def new
  end

  def show
  end

  def crawling
    if params[:site] == "snu"
      @article = Article.snu
    end
    @article = Article.all
    redirect_to articles_path
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.all
    @articles = Article.all
  end

  def new
    @notice = Notice.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]

  def index
  end

  def new
    if current_user
      @post = Post.new
    else
     flash[:alert] = "글 작성은 로그인이후 사용 가능합니다"
    end
  end

  def show
  end

  def create
    @post = Post.create!(post_params)
    if @post.save
      redirect_to root_path notice: "게시물이 생성되었습니다"
    else
      render "new"
    end
  end

  def edit
  end

  def update
    @post.update!(post_params)
    redirect_to post_path(@post.id)
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :content, :name)
  end

  def set_post
    @post = Post.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/articles/_table.html.erb
<table>
  <tr>
    <th>공지</th>
    <th>링크</th>
  </tr>
<% article.each do |p| %>
  <tr>
    <td><%= p.title %></td>
    <td><a href = '<%= p.url %>'>바로가기</a></td>
  </tr>
<% end %>
</table>

app/views/articles/index.html.erb
<%= link_to "Asian Analyse", root_path, style: "font-size: 30px;"%><br><br>
<%= link_to "새로고침", articles_path(site: "snu"), remote: true %>

<div class="article_list">
  <%= render "articles/table", article: @article %>
</div>
<%= paginate @article %>

app/views/articles/index.js.erb
$(".article_list").html("<%= j render 'articles/table', article: @article %>")

app/views/articles/new.html.erb
<h3> 크롤링 사이트 등록!</h3>

app/views/home/index.html.erb
<h1>Asian Analyse</h1>
<%= link_to "공지사항", new_home_path %><br>
<% if @articles.present? %> 
<%= link_to '크롤링', articles_path %>
<% else %>
    <p>아직 크롤링 한게 없습니다</p>
<% end %><br>
 
<%= link_to '게시판', new_post_path %><hr>
<% if @posts.present? %> 
<h3>게시판</h3>
  <table>
    <tr>
      <th>작성자</th>
      <th>제목</th>
      <th>내용</th>
      <th>보기</th>
      <th>수정</th>
      <th>삭제</th>
    </tr>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.name %></td>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= link_to '보기', post %></td>
        <td><%= link_to '수정', edit_post_path(post) %></td>
        <td><%= link_to '삭제', post_path(post), :confirm => 'Are you sure?', :method => :delete %></td>
      </tr>
    <% end %>
  </table>
<% else %>
    <p>아직 게시판이 없습니다</p>
<% end %>
 

app/views/home/new.html.erb
<h1>공지</h1>
<% @notice.each do |p|%>
  <h3>제목: <%= p.title %> <h3><hr>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrawlingPrac</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <% if current_user %>
      <%= link_to "로그아웃", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "로그인", new_user_session_path %>
      <%= link_to "회원가입", new_user_registration_path %>
    <% end %>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.js" integrity="sha256-BTlTdQO9/fascB1drekrDVkaKd9PkwBymMlHOiG+qLI=" crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  제목: <%= f.text_field :title %><br />
  내용 : <%= f.text_area :content %><br />
  <% f.hidden_field :author, value: current_user.name %>
  <%= f.submit "작성"%>
<% end %>

app/views/posts/edit.html.erb
<%= render 'posts/form' %>

app/views/posts/new.html.erb
<%= render 'posts/form' %>

app/views/posts/show.html.erb
<%= @post.id %> 번째 게시물<hr>

  제목: <%= @post.title %><br />
  내용 : <%= @post.content %><br />
  작성자 : <%= @post.name %><br /><br>

  <%= link_to "뒤로가기", root_path %>